### PR TITLE
fix: random npe caused by null list

### LINKED ISSUE #216: Irregular NPE on export
**Describe the bug**
Sometimes there is NPE for words list

```log
16:21:02.543 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=belligerent, title=Title[id=1076, name=Wool Omnibus, filter=1], createTime=1718392880, reviewTime=0, dueTime=1718393180, reviewCount=0, prevContext=him through a routine he?d seen twice before. Once with Jack Brent, who had been , nextContext= and hostile right up to the end, forcing him as sheriff to stand guard by the, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:02.716 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=crusade, title=Title[id=1, name=Orcs, filter=1], createTime=1694856977, reviewTime=0, dueTime=1694857277, reviewCount=0, prevContext=heed the Lord?s appeal we?ll be more than an army, we?ll be a , nextContext=.?
Mercy?s face had clouded at the mention of orcs. ?I hate them Wolverines,? she hissed, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:03.420 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=tinkle, title=Title[id=2, name=The Sorrows of Satan (Horror Classic), filter=1], createTime=1651481845, reviewTime=0, dueTime=1651482145, reviewCount=0, prevContext=null, nextContext=null, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:03.559 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=recline, title=Title[id=2, name=The Sorrows of Satan (Horror Classic), filter=1], createTime=1651867489, reviewTime=0, dueTime=1651867789, reviewCount=0, prevContext=null, nextContext=null, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:06.687 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=supplant, title=Title[id=3143, name=The Darkness That Comes Before, filter=1], createTime=1772520698, reviewTime=1772520698, dueTime=1772520998, reviewCount=0, prevContext=his students? adoration, and none more so than Inrau?s. Now the old master had been , nextContext=(supplanted). How could he rival a man who could command events such as this?
But somehow he, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:06.810 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=intrinsically, title=Title[id=2952, name=Accelerando, filter=1], createTime=1767077197, reviewTime=1767077197, dueTime=1767077497, reviewCount=0, prevContext=I am, clearly. You know ? I ascribe intentionality to you ? that my theory of mind is , nextContext= stronger than yours, that my cognitive model of human consciousness is complete. You might well suspect, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:11.705 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=oversee, title=Title[id=2952, name=Accelerando, filter=1], createTime=1763281586, reviewTime=1763281586, dueTime=1763281886, reviewCount=0, prevContext=but your companies do," she observes. "You have lawsuits, how many? You cannot the time to , nextContext= them spare. The Soviets, they abolish capitalists, but even they need managers. Please, let me manage, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:11.878 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=reproach, title=Title[id=1483, name=Ziska: The Problem of a Wicked Soul, filter=1], createTime=1721319247, reviewTime=0, dueTime=1721319547, reviewCount=0, prevContext=like you to see it too. Will you come??
 Denzil looked at him with a dark , nextContext= in his eyes.
 ?If you like,? he answered shortly.
 ?I do like!? and Gervase laid his, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:16.723 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=deadbeat, title=Title[id=743, name=The Dark Forest, filter=1], createTime=1715518099, reviewTime=1715518099, dueTime=1715518399, reviewCount=0, prevContext=whispered among themselves. Some of them seemed annoyed, while others flashed cryptic smiles.
?He?s a , nextContext=, a waste!? Rey Diaz said.
?Then what are you?? Tyler asked rudely, even though his mosquito, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:17.179 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=superlatively, title=Title[id=2, name=The Sorrows of Satan (Horror Classic), filter=1], createTime=1643909791, reviewTime=0, dueTime=1643910091, reviewCount=0, prevContext=null, nextContext=null, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:21.738 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=devoutly, title=Title[id=2, name=The Sorrows of Satan (Horror Classic), filter=1], createTime=1652101123, reviewTime=0, dueTime=1652101423, reviewCount=0, prevContext=null, nextContext=null, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:22.387 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=contemplative, title=Title[id=743, name=The Dark Forest, filter=1], createTime=1718045662, reviewTime=1718045662, dueTime=1718045962, reviewCount=0, prevContext=place before communication can resolve it.?
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:17.179 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=superlatively, title=Title[id=2, name=The Sorrows of Satan (Horror Classic), filter=1], createTime=1643909791, reviewTime=0, dueTime=1643910091, reviewCount=0, prevContext=null, nextContext=null, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:21.738 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=devoutly, title=Title[id=2, name=The Sorrows of Satan (Horror Classic), filter=1], createTime=1652101123, reviewTime=0, dueTime=1652101423, reviewCount=0, prevContext=null, nextContext=null, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:22.387 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=contemplative, title=Title[id=743, name=The Dark Forest, filter=1], createTime=1718045662, reviewTime=1718045662, dueTime=1718045962, reviewCount=0, prevContext=place before communication can resolve it.?
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:21.738 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=devoutly, title=Title[id=2, name=The Sorrows of Satan (Horror Classic), filter=1], createTime=1652101123, reviewTime=0, dueTime=1652101423, reviewCount=0, prevContext=null, nextContext=null, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:22.387 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=contemplative, title=Title[id=743, name=The Dark Forest, filter=1], createTime=1718045662, reviewTime=1718045662, dueTime=1718045962, reviewCount=0, prevContext=place before communication can resolve it.?
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:22.387 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=contemplative, title=Title[id=743, name=The Dark Forest, filter=1], createTime=1718045662, reviewTime=1718045662, dueTime=1718045962, reviewCount=0, prevContext=place before communication can resolve it.?
 createTime=1718045662, reviewTime=1718045662, dueTime=1718045962, reviewCount=0, prevContext=place before communication can resolve it.?
Shi Qiang took a drag on his cigarette, and his , nextContext= face emerged from the darkness for a moment. ?It looks now like the Battle of Darkness, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:26.758 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=conceal, title=Title[id=2, name=The Sorrows of Satan (Horror Classic), filter=1], createTime=1645907565, reviewTime=0, dueTime=1645907865, reviewCount=0, prevContext=null, nextContext=null, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
16:21:26.867 [ForkJoinPool.commonPool-worker-1] ERROR r.d.k.c.s.e.ExporterServiceAnkiVirtualThreadsCF - Something went wrong with word: Vocabulary[word=deference, title=Title[id=1, name=Orcs, filter=1], createTime=1694981168, reviewTime=0, dueTime=1694981468, reviewCount=0, prevContext=There was an understandable frigidity in the tone he used with her, but also a greater , nextContext=.
?How reliable is this information??
?It was a night sighting, Majesty, so there is some room, streakCount=0]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "words" is null
```

**To Reproduce**
Try to export something. You could or could not get such messages. 

Possible cause - rest client timeouts.

**Expected behavior**
No npe should be present. At least empty words list.

**Additional context**
Problem is in `AnkiConverterServiceCompletableFuture` class probably. Http service gets some exception it can't handle, therefore it doesn't return anything (null). 

As for solution, such words should be ignored, and removed from state. Also it would be good to add logs for export into some file because reading it from terminal is uncomfortable.

### PR DESCRIPTION
**Pull request by Dankoy**
# Description

1) Added retry using resilience4j for dictionary-api service. It retries only 
    - org.springframework.web.reactive.function.client.WebClientResponseException
    - org.springframework.web.reactive.function.client.WebClientRequestException
2) Fixed logic in AnkiConverterServiceCompletableFuture to correctly catch exceptions above (if retry exhausts) then use empty word.
3) Added logging into separate file for full-log.shell
4) Added tests, including retry logic tests.
5) Added logging for retry events.
6) Updated release to 0.5.0

> [!WARNING]
> In some cases there are same npe, but i couldn't find it after full export of 4500 words.
> Debugged export for two days, couldn't get what is randomly causing it. 
> But most of exceptional events which leads to this NPE has been fixed with this PR

Fixes #216

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Full export for 4500 words. Everything should be fine.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/test/java/ru/dankoy/korvotoanki/core/service/dictionaryapi/DictionaryServiceOkHttpTest.java [hunk 1]
```diff
@@ -41,6 +43,7 @@
     })
 @ExtendWith(MockitoExtension.class) // necessary for @Mock annotation to work
 @TestPropertySource(properties = "korvo-to-anki.http-client=ok-http")
+@DirtiesContext(classMode = ClassMode.AFTER_CLASS)
```
Comment (Dankoy) [inline src/test/java/ru/dankoy/korvotoanki/core/service/dictionaryapi/DictionaryServiceOkHttpTest.java]: This is not needed.

**Review by Dankoy — COMMENTED** [review]
ok
